### ISSUE TITLE
Pods_LiveSDK_iOS 找不到，PLVLiveSDK多个类报错

### ISSUE THREAD

**Issue by NicholasBxt** [polyv/polyv-ios-live-sdk#3]

**Comment by Zeaa** [comment]
此项目已经不再更新了，直播SDK使用以下两个
普通直播 [demo-SDK](https://github.com/easefun/polyv-ios-liveplayer)
云课堂直播（建议，持续更新维护）  [demo-SDK](https://github.com/polyv/polyv-ios-cloudClass-sdk-demo)
